ddev/ddev-intellij-plugin

.github/workflows/tests.yml
build.gradle.kts

Closes #62
This PR's HEAD is based on #93
SonarCloud Coverage acutally works but the message it left in this PR says No Coverage Information because `main` currently has none. Their Website actually shows
> 35.3% Estimated after merge

Re-enable test coverage report

---

src/main/java/de/php_perfect/intellij/ddev/php/PhpInterpreterProviderImpl.java

To ensure the Docker compose based php interpreter is working a docker remote server has to be configured.
- #92

Create docker remote server if it does not exist

---

src/main/java/de/php_perfect/intellij/ddev/database/DataSourceProviderImpl.java
src/test/java/de/php_perfect/intellij/ddev/database/DataSourceProviderTest.java

* #106
When using maridb as database the dsn will now be jdbc:mariadb instead of jdbc:mysql as described in
https://mariadb.com/kb/en/about-mariadb-connector-j/#jdbcmysql-scheme-compatibility

Fix mariadb specific dsn type

---

build.gradle.kts

Test run locally or in GitHub Actions fail with an error/exception.
This PR adds `org.junit.platform:junit-platform-launcher` as a `testRuntimeOnly`-dependency fixing a `NoClassDefFoundError` that occurs when trying to run the tests
Run `./gradlew test --stacktrace --info jacocoTestReport`
\-

Fix failing unit tests by adding `junit-platform-launcher` as dependency

---

.github/workflows/tests.yml

The upload steps are skipped if the tests fail.
This should obviously not happen because reports get especially interesting with test failures.
By using `always()` ([docs](https://docs.github.com/en/actions/learn-github-actions/expressions#always)) as a step's run condition, we can ensure that it is run even on test failures.
1. Have failing tests in the pipeline
2. Check if test reports get uploaded as artifacts anyway
3. Check if coverage report is still only being uploaded for Ubuntu/Linux
\-

GitHub Actions: Upload test reports even when tests fail

---

src/main/java/de/php_perfect/intellij/ddev/database/DataSourceProviderImpl.java

#122
The newly generated TreePatern will index all schemas.

Configure DataSource TreePattern to index all schemas

---

src/main/java/de/php_perfect/intellij/ddev/dockerCompose/DockerComposeCredentialProviderImpl.java

The Docker credentials configuration created by this plugin did not include the environment variables of the parent process which could lead to a
""docker.exe": executable file not found in %PATH%" error.
Include parent process environment variables for the created docker credentials holder.
* #187

Fix Docker.exe not found error

---

src/main/java/de/php_perfect/intellij/ddev/cmd/Ddev.java
src/main/java/de/php_perfect/intellij/ddev/cmd/DdevImpl.java
src/main/java/de/php_perfect/intellij/ddev/errorReporting/SentryErrorReporter.java
src/main/java/de/php_perfect/intellij/ddev/state/DdevStateManagerImpl.java
src/main/java/de/php_perfect/intellij/ddev/state/State.java
src/main/java/de/php_perfect/intellij/ddev/state/StateImpl.java
src/main/java/de/php_perfect/intellij/ddev/version/VersionCheckerImpl.java
src/main/java/de/php_perfect/intellij/ddev/version/util/VersionCompare.java
src/test/java/de/php_perfect/intellij/ddev/cmd/DdevImplTest.java
src/test/java/de/php_perfect/intellij/ddev/state/DdevStateManagerTest.java
src/test/java/de/php_perfect/intellij/ddev/version/util/VersionCompareTest.java

Use --version to retrieve the version of the ddev binary and collect debug data via version only on error reports.
The plugin is using `ddev version` to collect information about the current binary of ddev as well as 3rd party binary versions to use them for debugging purposes in case of an error.
This command requires docker to run and is not very performant.
To boostrap the plugin, the presence of ddev is checked using `ddev --version` and in case of a error report the output of `ddev version` is parsed.
Thanks to @rfay for suggesting this change.

Update ddev version check for better performance

---

src/main/java/de/php_perfect/intellij/ddev/notification/DdevNotifierImpl.java
src/main/java/de/php_perfect/intellij/ddev/version/Version.java

The versions listed in the update notifications are displayed as Java Objects instead of the version string.
Implement toString method for the version object.
Use an old ddev version and check the update notification.

Fix display issue of the ddev version in the update notification

---

src/main/java/de/php_perfect/intellij/ddev/cmd/DdevShellCommandHandlerImpl.java
src/main/resources/META-INF/plugin.xml
src/test/java/de/php_perfect/intellij/ddev/cmd/DdevShellCommandHandlerTest.java

Ddev commands executed in the terminal do not trigger an update of the ddev status in the plugin.
By highlighting ddev commands and suggesting executing them by the plugin people might use this way to get a better expereince.
Ddev commands typed in a terminal window get highlighted and can be executed by the Plugin pressing Ctrl + Enter.

Add highlighting for ddev commands that can be executed in ui

---

src/main/java/de/php_perfect/intellij/ddev/cmd/RunnerImpl.java

`NON_MODAL` has been deprecated: https://github.com/JetBrains/intellij-community/blob/0c1f99dc08e1542c4f0da0e2361ac0599849ffa7/platform/core-api/src/com/intellij/openapi/application/ModalityState.java#L40-L43
Migrated `NON_MODAL` to `nonModal()` according to the suggestion in `@deprecated`.
None.
None.

refactor(cmd): Call nonModal() instead of NON_MODAL constant

---

src/main/java/de/php_perfect/intellij/ddev/icons/DdevIntegrationIcons.java

According to <https://github.com/JetBrains/intellij-community/blob/0c1f99dc08e1542c4f0da0e2361ac0599849ffa7/platform/util/src/com/intellij/ui/IconManager.kt#L53-L54>,
the `fun getIcon(path: String, aClass: Class<*>): Icon` signature has been deprecated.
Migrate it to `fun getIcon(path: String, classLoader: ClassLoader): Icon`.
Tested manually in #242:
None.

refactor(icons): Use the ClassLoader overload of getIcon

---

src/main/java/de/php_perfect/intellij/ddev/cmd/DatabaseInfo.java
src/main/java/de/php_perfect/intellij/ddev/database/AutoConfigureDataSourceListener.java
src/main/java/de/php_perfect/intellij/ddev/database/DataSourceConfig.java
src/main/java/de/php_perfect/intellij/ddev/database/DataSourceProvider.java
src/main/java/de/php_perfect/intellij/ddev/database/DataSourceProviderImpl.java
src/main/java/de/php_perfect/intellij/ddev/database/DdevDataSourceManager.java
src/main/java/de/php_perfect/intellij/ddev/database/DdevDataSourceManagerImpl.java
src/main/java/de/php_perfect/intellij/ddev/dockerCompose/DockerComposeConfig.java
src/main/java/de/php_perfect/intellij/ddev/dockerCompose/DockerComposeCredentialProvider.java
src/main/java/de/php_perfect/intellij/ddev/dockerCompose/DockerComposeCredentialProviderImpl.java
src/main/java/de/php_perfect/intellij/ddev/index/IndexEntry.java
src/main/java/de/php_perfect/intellij/ddev/index/IndexableConfiguration.java
src/main/java/de/php_perfect/intellij/ddev/index/ManagedConfigurationIndex.java
src/main/java/de/php_perfect/intellij/ddev/index/ManagedConfigurationIndexImpl.java
src/main/java/de/php_perfect/intellij/ddev/node/NodeInterpreterConfig.java
src/main/java/de/php_perfect/intellij/ddev/node/NodeInterpreterProvider.java
src/main/java/de/php_perfect/intellij/ddev/node/NodeInterpreterProviderImpl.java
src/main/java/de/php_perfect/intellij/ddev/php/DdevInterpreterConfig.java
src/main/java/de/php_perfect/intellij/ddev/php/PhpInterpreterProvider.java
src/main/java/de/php_perfect/intellij/ddev/php/PhpInterpreterProviderImpl.java
src/main/java/de/php_perfect/intellij/ddev/php/server/ServerConfig.java
src/main/java/de/php_perfect/intellij/ddev/php/server/ServerConfigManagerImpl.java
src/main/resources/META-INF/plugin.xml
src/test/java/de/php_perfect/intellij/ddev/database/DataSourceProviderTest.java
src/test/java/de/php_perfect/intellij/ddev/index/ManagedConfigurationIndexTest.java
src/test/java/de/php_perfect/intellij/ddev/php/server/ServerConfigManagerImplTest.java

This index allows to identify automatically generated configurations without the need of a naming pattern.
This adresses the problem of unnecessarily overwritten configurations and the need of the "DDEV" naming for generated configurations.
The pull request includes the migration of the PHP server configuration management to the new configuration management index.
The ddev plugin references generated by configurations by their name "DDEV" this does not allow the name to change based on settings, as the relation would go lost. This is why the php server configuration could not be named by the fqdn till now.
This PR is changing the name of the generated php server configuration to the fqdn of the ddev project. This is made possible by the configuration management index.
* …

Add index for generated configurations

---

build.gradle.kts
src/main/resources/META-INF/plugin.xml

This plugin is incompatible with 2023.3 EAP.
Upgrade extension versions to EAP.
Build integrated with #238, #239, #240, #241: 
[ddev-intellij-plugin-1.1.2-EAP.2.zip](https://github.com/php-perfect/ddev-intellij-plugin/files/12813162/ddev-intellij-plugin-1.1.2-EAP.2.zip)

Add support of EAP build (233.*)

---

src/main/java/de/php_perfect/intellij/ddev/database/DataSourceProviderImpl.java
src/test/java/de/php_perfect/intellij/ddev/database/DataSourceProviderTest.java

#278
- `mysql.8` driver is used for any MySQL database with version >= 5.2
1. Create new ddev project with `ddev config --database mysql:5.7`
2. Run `ddev start`
3. Launch IntelliJ with updated plugin
4. Confirm no database errors are thrown and confirm "DDEV" data source is using the "MySQL supports since 5.2" driver
fixes #278

Fix mysql driver selection

---

src/main/java/de/php_perfect/intellij/ddev/dockerCompose/DockerComposeCredentialProviderImpl.java

Docker-compose doesn't supports upper case letters, so the existing container cannot be found.
The project name must be in lowercase even the project name itself contains uppercase letters.
Create a ddev project with uppercase letters
https://discord.com/channels/664580571770388500/1239527694371131403/1239527694371131403

Project name in env variable must be in lowercase

---

src/main/java/de/php_perfect/intellij/ddev/version/GithubClient.java

Resolves issue #326
redirectLimit has a misleading name, and actually requires a value of 1 + redirect limit.
See relevant HttpRequests code at https://github.com/JetBrains/intellij-community/blob/401226d2da0fff5e7996911fb2370cff7f66180a/platform/ide-core/src/com/intellij/util/io/HttpRequests.java#L552
and IntelliJ Community test suite at https://github.com/JetBrains/intellij-community/blob/451d49f1dde29a396096d1ed7c761c6afab62e68/platform/platform-tests/testSrc/com/intellij/util/io/HttpRequestsTest.kt#L89
./gradlew build
Install resulting build/distributions/ddev-intellij-plugin-0.0.1-dev.zip
No more redirect exception on program start

Fix redirect limit in update check

---

src/main/java/de/php_perfect/intellij/ddev/statusBar/DdevStatusBarWidgetFactoryImpl.java
src/main/java/de/php_perfect/intellij/ddev/statusBar/DdevStatusBarWidgetImpl.java
src/main/resources/META-INF/plugin.xml

Resolves issue #296 
Rework the status bar widget implementation to extend EditorBasedStatusBarPopup and StatusBarEditorBasedWidgetFactory respectively instead & remove code handled in the parent class
Use same static ID for the widget in DdevStatusBarWidgetImpl and plugin.xml
- ./gradlew build
- Install resulting build/distributions/ddev-intellij-plugin-0.0.1-dev.zip
- Toggling visibility of the ddev widget should work identical to all first-party widgets and cause no exceptions
- To test if the tutorial popup is still appearing properly, a tutorial reset might be required. This can be done by removing the got.it.tooltip.ddev entries from options/other.xml within the global IDE directory and restarting the program
e.g. ~/.config/JetBrains/PhpStorm2024.2/options/other.xml for PhpStorm …

Fix visibility change in statusbar

---

src/main/java/de/php_perfect/intellij/ddev/cmd/ProcessExecutorImpl.java

Resolve #313
By providing an EmptyProgressIndicator, functionality is maintained while satisfying the cause of the warning.
Maybe it can be solved more elegantly, but the current version is the most concise way I could find.
The chosen solution is marked as obsolete due to the strong suggestion by JetBrains to move to Kotlin.
Open a Windows installation of an IDE and load a project stored on WSL.
Without the patch, warnings appear due to the background executions, with the patch, they no longer appear.

Prevent ProgressIndicator warnings by using an EmptyProgressIndicator

---

src/main/java/de/php_perfect/intellij/ddev/node/AutoConfigureNodeInterpreterListener.java

The node.js binary path is incorrect for DDEV version 1.23.4, where the path changed from /usr/bin/node to /usr/local/bin/node.
This change sets the node binary without an absolute path. That way, functionality is ensured across DDEV versions without having to check the currently running version. This setup also matches the JetBrains documentation examples of setting up node.js docker compose remote interpreter.
Remove the node.js DDEV connection
Close and reopen the project
Check the configuration, it should only refer to "node" as path
Test node functionality
#353

Change autoconfiguration of node.js binary path to node

---

gradle.properties
src/main/java/de/php_perfect/intellij/ddev/settings/DdevSettingsComponent.java
src/test/java/de/php_perfect/intellij/ddev/terminal/DdevTerminalRunnerTest.java

Resolves issue #379 
Raise platformVersion to 2024.3
Minor code adaptations to match current function signatures
./gradlew build
Install resulting build/distributions/ddev-intellij-plugin-0.0.1-dev.zip
Test functionality in PhpStorm / IntelliJ

Update build for 2024.3 support

---

src/main/java/de/php_perfect/intellij/ddev/dockerCompose/DockerComposeCredentialProviderImpl.java

Auto config breaks if project contains period . #367
See https://github.com/php-perfect/ddev-intellij-plugin/issues/367#issuecomment-2393735285

Fix COMPOSE_PROJECT_NAME period issue #367

---

src/main/java/de/php_perfect/intellij/ddev/actions/OpenServiceAction.java
src/main/java/de/php_perfect/intellij/ddev/actions/ReportIssueAction.java
src/main/java/de/php_perfect/intellij/ddev/php/server/ServerConfig.java
src/main/java/de/php_perfect/intellij/ddev/php/server/ServerConfigManagerImpl.java
src/main/java/de/php_perfect/intellij/ddev/serviceActions/ServiceActionManagerImpl.java
src/main/java/de/php_perfect/intellij/ddev/tutorial/GotItTutorialImpl.java
src/test/java/de/php_perfect/intellij/ddev/serviceActions/ServiceActionManagerImplTest.java

Resolves #392 
Replace URL with URI where possible, implicitly fixing hashing and comparison collisions between URLs with different hostnames that resolve to the same IP address.
- Set up a new DDEV project
- Add an additional service, e.g. `ddev add-on get ddev/ddev-solr`
- Configure the service to use the same ports as the web container (80 & 443), but with a different hostname:
```
VIRTUAL_HOST: solr.${DDEV_HOSTNAME}
HTTP_EXPOSE: 80:8983
HTTPS_EXPOSE: 443:8983
```
- `ddev start`
- The web and solr service names are no longer set to the same value, randomly changing, as displayed below:

Switch to URI where possible

---

src/main/java/de/php_perfect/intellij/ddev/database/AutoConfigureDataSourceListener.java
src/main/java/de/php_perfect/intellij/ddev/node/AutoConfigureNodeInterpreterListener.java
src/main/java/de/php_perfect/intellij/ddev/notification/DdevNotifier.java
src/main/java/de/php_perfect/intellij/ddev/notification/DdevNotifierImpl.java
src/main/java/de/php_perfect/intellij/ddev/php/ConfigurationProviderImpl.java
src/main/java/de/php_perfect/intellij/ddev/settings/DdevSettingsComponent.java
src/main/java/de/php_perfect/intellij/ddev/util/FeatureRequiredPlugins.java
src/main/java/de/php_perfect/intellij/ddev/util/PluginChecker.java
src/main/java/de/php_perfect/intellij/ddev/util/PluginDisplayNameMapper.java
src/main/resources/META-INF/DdevIntegration-withDocker.xml
src/main/resources/META-INF/DdevIntegration-withNodeRemoteInterpreter.xml
src/main/resources/META-INF/DdevIntegration-withPhp.xml
src/main/resources/META-INF/plugin.xml
src/main/resources/messages/DdevIntegrationBundle.properties
src/test/java/de/php_perfect/intellij/ddev/notification/DdevNotifierTest.java

* #402 
Completely reworked the dependency checks, and how they're being presented.
- Required Plugin dependencies:
- Remote Execution Agent (intellij.platform.ijent.impl)
- Docker
- Optional Plugin dependencies:
- Terminal (plugin.name.terminal)
- Dependencies for PHP auto-configure:
- PHP (com.jetbrains.php)
- PHP Docker (org.jetbrains.plugins.phpstorm-remote-interpreter)
- PHP Remote Interpreter (org.jetbrains.plugins.phpstorm-docker)
- Dependencies for node.js auto-configure:
- Node.js (NodeJS)
- Node.js Remote Interpreter (org.jetbrains.plugins.node-remote-interpreter)
- Dependencies for database auto-configure:
- Database Tools and SQL (com.intellij.database)
Install [ddev-intellij-plugin-0.0.1-dev.zip](https://github.com/user-attachments/files/19985565/ddev-intellij-plugin-0.0.1-dev …

fix: update plugin dependency checks and notifications, fixes #402

---

src/main/java/de/php_perfect/intellij/ddev/version/Version.java
src/test/java/de/php_perfect/intellij/ddev/cmd/DdevImplTest.java
src/test/java/de/php_perfect/intellij/ddev/version/VersionTest.java

Currently, ddev head versions that report a version like `ddev version v1.24.4-36-ge74e3a95f` are not supported by the plugin.
Updated the version parsing to handle head versions.
Download a DDEV head version: https://ddev.readthedocs.io/en/stable/developers/building-contributing/#testing-latest-commits-on-head
Change the DDEV settings in PhpStorm to use the head version path (/usr/local/bin/ddev)
Check if the plugin still works

feat: update version detection to support ddev head version

---

src/main/java/de/php_perfect/intellij/ddev/database/DdevDataSourceManagerImpl.java

Sometimes a "Ref count mismatch" exception was produced on opening a project since the update to 2025.2
Removed the manual creation of a Continuation object with EmptyCoroutineContext.INSTANCE that was causing reference counting issues in IntelliJ's AsyncTask framework, leading to the "Ref count mismatch" assertion error.

fix: remove problematic manual database introspection causing ref count mismatch

---

src/main/java/de/php_perfect/intellij/ddev/php/composer/DdevComposerExecution.java
src/main/java/de/php_perfect/intellij/ddev/php/composer/DdevComposerExecutionProvider.java
src/main/java/de/php_perfect/intellij/ddev/php/composer/DdevComposerForm.java
src/main/java/de/php_perfect/intellij/ddev/php/composer/DdevComposerProcessHandler.java
src/main/resources/META-INF/DdevIntegration-withPhp.xml
src/main/resources/messages/DdevIntegrationBundle.properties

The docker compose remote interpreter for IntelliJ automatically starts the docker services, which hinders regular DDEV use. Additionally, use the regular PHP calls, we're initializing unwanted debugging connections with every call to composer.
Adding a dedicated DDEV executor to the composer setting circumvents the issue, since we can prevent unwanted calls to docker compose, and instead use ddev composer for running the composer commands. Which also solves the issue of xDebug sessions being started on all composer interactions.
#441

feat: add experimental ddev executor for composer
